Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
    - app/**/**
  Excludes:
    - config/**
    - script/**
    - bin/**
    - app/assets/config/manifest.js