development:
  cloud_name: dyqhyadw6
  api_key: '944291334932193'
  api_secret: _1DDXSYvfw_0CVqzBYyedaMzXkA
  enhance_image_tag: true
  static_file_support: false
  
production:
  cloud_name: dyqhyadw6
  api_key: '944291334932193'
  api_secret: _1DDXSYvfw_0CVqzBYyedaMzXkA
  enhance_image_tag: true
  static_file_support: true

test:
  cloud_name: dyqhyadw6
  api_key: '944291334932193'
  api_secret: _1DDXSYvfw_0CVqzBYyedaMzXkA
  enhance_image_tag: true
  static_file_support: false
